Repository temporalio/documentation, pull requests merged in 2024-12, with the labels that each got.

#3209 EDU-3543: [PHP] Document next retry delay
  docs/develop/java/failure-detection.mdx
  docs/develop/php/failure-detection.mdx
  docs/references/failures.mdx
Labels: tracked-internally, community-contributor

#3222 EDU-3639: removed import docs
  docs/production-deployment/cloud/terraform-provider.mdx
Labels: tracked-internally, cross-team

#3221 EDU-3642: Include GCP in MRN documentation
  docs/evaluate/development-production-features/multi-region-namespace.mdx
  docs/production-deployment/cloud/multi-region.mdx
Labels: tracked-internally, cross-team

#3203 EDU-3508: [PHP] Improve docs about client
  docs/develop/php/core-application.mdx
  docs/develop/php/index.mdx
  docs/develop/php/temporal-clients.mdx
Labels: tracked-internally, community-contributor

#3207 EDU-3544: [PHP] Update Message passing page
  docs/develop/php/index.mdx
  docs/develop/php/message-passing.mdx
Labels: tracked-internally, community-contributor

#3227 EDU-955: Change SSO mentions from Azure AD to MS Entra ID
  docs/production-deployment/cloud/account-setup/users.mdx
  docs/production-deployment/cloud/saml.mdx
Labels: waiting-on-team-review

#3225 EDU-2227: Adds quick reference to visibility page
  docs/encyclopedia/visibility.mdx
Labels: waiting-on-team-review

#3196 EDU-3400: Update Nexus docs
  docs/develop/go/index.mdx
  docs/develop/go/temporal-nexus.mdx
  docs/develop/java/index.mdx
  docs/develop/java/temporal-nexus.mdx
  docs/encyclopedia/nexus-endpoints.mdx
  docs/encyclopedia/nexus-error-handling.mdx
  docs/encyclopedia/nexus-execution-debugging.mdx
  docs/encyclopedia/nexus-metrics.mdx
  docs/encyclopedia/nexus-operations.mdx
  docs/encyclopedia/nexus-registry.mdx
  docs/encyclopedia/nexus-security.mdx
  docs/encyclopedia/nexus-services.mdx
  docs/encyclopedia/nexus-use-cases.mdx
  docs/encyclopedia/nexus.mdx
  docs/encyclopedia/temporal-nexus-api-registry-endpoints.mdx
  docs/encyclopedia/temporal-nexus-service-operations.mdx
  docs/encyclopedia/temporal-nexus.mdx
  docs/evaluate/development-production-features/temporal-nexus.mdx
  docs/glossary.md
  docs/production-deployment/cloud/index.mdx
  docs/production-deployment/cloud/nexus/getting-started.mdx
  docs/production-deployment/cloud/nexus/index.mdx
  docs/production-deployment/cloud/nexus/latency-availability.mdx
  docs/production-deployment/cloud/nexus/limits.mdx
  docs/production-deployment/cloud/nexus/observability.mdx
  docs/production-deployment/cloud/nexus/operations.mdx
  docs/production-deployment/cloud/nexus/pricing.mdx
  docs/production-deployment/cloud/nexus/security.mdx
  docs/production-deployment/cloud/nexus/using-nexus.mdx
  docs/production-deployment/self-hosted-guide/index.mdx
  docs/production-deployment/self-hosted-guide/temporal-nexus.mdx
  sidebars.js
  static/img/NexusAPIRegistry.png
  static/img/nexus-overview-short.png
  static/img/nexus-overview.png
  static/img/nexus/NexusYourCloud.png
  static/img/nexus/nexus-async-operation.png
  static/img/nexus/nexus-bi-directional-linking.png
  static/img/nexus/nexus-sync-operation-arbitrary-code.png
  static/img/nexus/nexus-sync-operation.png
  static/img/nexus/nexus-workers-short-async-op-sequence.png
  static/img/nexus/nexus-workers-short-sync-op-sequence.png
  static/img/nexus/nexus-workers-short.png
  static/img/nexus/nexus-workers.png
Labels: tracked-internally, cross-team

#3178 EDU-3363: Add section on how to run Nexus sample with API key
  docs/develop/go/temporal-nexus.mdx
Labels: tracked-internally, cross-team

#3234 EDU-3690: Clarify that Activities and Child Workflows that exhaust their retries will cause Update / Workflow to fail.
  docs/encyclopedia/application-message-passing.mdx
Labels: tracked-internally, cross-team

#3120 EDU-3236: Update-with-Start
  docs/develop/go/message-passing.mdx
  docs/develop/java/message-passing.mdx
  docs/encyclopedia/application-message-passing.mdx
  vale/styles/Temporal/terms.yml
Labels: tracked-internally, blocked-on-release, cross-team

#3245 EDU-2602: Add "Replication Lag" to the Glossary
  docs/glossary.md
Labels: bug bash, docs-cember

#3233 EDU-3694: Workflow Update
  docs/develop/go/message-passing.mdx
  docs/encyclopedia/application-message-passing.mdx
Labels: cross-team, waiting-on-ticket, development-in-progress

#3027 Changing remaining cloud links to ssu
  docs/production-deployment/cloud/operation-api.mdx
Labels: docs-cember

#3253 EDU-3717: versioning.mdx typo
  docs/develop/java/versioning.mdx
Labels: bug bash, docs-cember

#2974 Use cases and design patterns under evaluate
  docs/evaluate/index.mdx
  docs/evaluate/use-cases-design-patterns.mdx
  sidebars.js
Labels: docs-cember

#3250 EDU-3715: Python update-with-start docs
  docs/develop/go/message-passing.mdx
  docs/develop/java/message-passing.mdx
  docs/develop/python/message-passing.mdx
  docs/encyclopedia/application-message-passing.mdx
Labels: tracked-internally, blocked-on-release, cross-team
