Repository temporalio/documentation, pull requests merged in 2025-01, with the labels that each got.

#3238 EDU-2441: Updates keyword docs to mention starts_with prefix
  docs/encyclopedia/visibility.mdx
Labels: waiting-on-team-review

#3271 fix: example link
  docs/develop/java/schedules.mdx
Labels: community-contributor

#3265 EDU-3740: doc(): update doc to show that actual value measured in bytes
  docs/references/dynamic-configuration.mdx
Labels: tracked-internally, community-contributor

#3264 EDU-3742: temporal-cloud-metrics: add scrape interval details
  docs/production-deployment/cloud/metrics/reference.mdx
Labels: tracked-internally, cross-team

#3261 EDU-3537: Backport info on search attributes and patching from Java Versioning Workflows course
  docs/develop/java/versioning.mdx
Labels: cross-team, bug bash, docs-cember, tracking-internally

#3259 EDU-3744: Doc links to Update with Start, .NET
  docs/encyclopedia/application-message-passing.mdx
Labels: cross-team, tracking-internally

#3258 EDU-3673: Update .NET Determinism update documentation to be inline with the README.md
  docs/develop/dotnet/core-application.mdx
Labels: cross-team, bug bash, docs-cember, tracking-internally

#3279 EDU-3733: Add auto failover information to MRN page
  docs/production-deployment/cloud/multi-region.mdx
Labels: revising

#3262 EDU-3743: Typescript update-with-start
  docs/develop/typescript/message-passing.mdx
  docs/encyclopedia/application-message-passing.mdx
Labels: cross-team, tracking-internally

#3276 EDU-3747: Add Temporal Auth Scopes for web ui docker env vars
  docs/references/web-ui-environment-variables.mdx
  docs/references/web-ui-server-env-vars.mdx
Labels: community-contributor, tracking-internally, issue-link

#3270 EDU-3427: Project Nova: Worker pg break out including redirects and anchors
  docs/cli/task-queue.mdx
  docs/cli/workflow.mdx
  docs/develop/dotnet/core-application.mdx
  docs/develop/dotnet/failure-detection.mdx
  docs/develop/dotnet/temporal-client.mdx
  docs/develop/go/core-application.mdx
  docs/develop/go/failure-detection.mdx
  docs/develop/go/schedules.mdx
  docs/develop/go/sessions.mdx
  docs/develop/go/temporal-client.mdx
  docs/develop/go/versioning.mdx
  docs/develop/java/core-application.mdx
  docs/develop/java/failure-detection.mdx
  docs/develop/java/temporal-client.mdx
  docs/develop/java/versioning.mdx
  docs/develop/php/core-application.mdx
  docs/develop/php/failure-detection.mdx
  docs/develop/python/core-application.mdx
  docs/develop/python/failure-detection.mdx
  docs/develop/python/temporal-clients.mdx
  docs/develop/python/versioning.mdx
  docs/develop/typescript/core-application.mdx
  docs/develop/typescript/failure-detection.mdx
  docs/develop/typescript/temporal-clients.mdx
  docs/develop/typescript/testing-suite.mdx
  docs/develop/typescript/versioning.mdx
  docs/develop/worker-performance.mdx
  docs/encyclopedia/activities.mdx
  docs/encyclopedia/clusters.mdx
  docs/encyclopedia/detecting-activity-failures.mdx
  docs/encyclopedia/detecting-workflow-failures.mdx
  docs/encyclopedia/namespaces.mdx
  docs/encyclopedia/nexus-error-handling.mdx
  docs/encyclopedia/nexus-metrics.mdx
  docs/encyclopedia/nexus-operations.mdx
  docs/encyclopedia/nexus.mdx
  docs/encyclopedia/retry-policies.mdx
  docs/encyclopedia/worker-versioning-legacy.mdx
  docs/encyclopedia/workers.mdx
  docs/encyclopedia/workers/sticky-execution.mdx
  docs/encyclopedia/workers/task-queues.mdx
  docs/encyclopedia/workers/task-routing-worker-sessions.mdx
  docs/encyclopedia/workers/tasks.mdx
  docs/encyclopedia/workers/worker-versioning.mdx
  docs/encyclopedia/workers/workers.mdx
  docs/encyclopedia/workflows.mdx
  docs/glossary.md
  docs/production-deployment/cloud/account-setup/namespaces.mdx
  docs/production-deployment/cloud/nexus/latency-availability.mdx
  docs/references/commands.mdx
  docs/references/errors.mdx
  docs/references/events.mdx
  docs/tctl-v1/admin.mdx
  docs/tctl-v1/index.mdx
  docs/tctl-v1/taskqueue.mdx
  docs/tctl-v1/workflow.mdx
  docs/web-ui.mdx
  sidebars.js
  vercel.json
Labels: waiting-on-team-review

#3244 change passive voice to active voice pricing pg
  docs/evaluate/temporal-cloud/pricing.mdx
Labels: waiting-on-team-review, bug bash, docs-cember

#3266 provide update to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: waiting-on-team-review

#3246 EDU-2392: Removing repetitive code snippet
  docs/develop/python/versioning.mdx
Labels: docs-cember, ready-to-merge

#3284 EDU-3170: Updates Worker Task Queue coverage for Nexus
  docs/develop/worker-performance.mdx
  docs/encyclopedia/workers/task-queues.mdx
  static/img/encyclopedia/workers/nexus-task-queue.png
Labels: waiting-on-team-review

#3080 EDU-709 - Gcp features for AFTER REPLAY
  docs/evaluate/temporal-cloud/gcp-private-service-connect.mdx
  docs/production-deployment/cloud/audit-logging-gcp.mdx
  docs/production-deployment/cloud/audit-logging.mdx
  docs/production-deployment/cloud/aws-export-s3.mdx
  docs/production-deployment/cloud/export.mdx
  docs/production-deployment/cloud/gcp-export-gcs.mdx
  sidebars.js
  static/img/export-sink-ui-gcp.png
  static/img/export-sink-ui.png
  static/img/gcp-private-service-connect/connect-endpoint-button.png
  static/img/gcp-private-service-connect/connect-endpoint.png
  static/img/gcp-private-service-connect/gcp-console.png
Labels: work-in-progress

#3280 EDU-3746: Adds reasons to trigger MRN failovers for testing
  docs/production-deployment/cloud/multi-region.mdx
Labels: waiting-on-team-review

#3293 Adding replay announcement banner 🇬🇧
  docusaurus.config.js
Labels: ready-to-merge

#3296 fix typo in activities.mdx
  docs/encyclopedia/activities.mdx
Labels: ready-to-merge

#3290 EDU-3751: Improves Issue UX
  .github/ISSUE_TEMPLATE/0_typos-and-grammar.yml
  .github/ISSUE_TEMPLATE/1_technical-issues.yml
  .github/ISSUE_TEMPLATE/2_content-issues.yml
  .github/ISSUE_TEMPLATE/3_improvement-suggestions.yml
  .github/ISSUE_TEMPLATE/4_accessibility-issues.yml
  .github/ISSUE_TEMPLATE/5_other-feedback.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation-request.md
  .github/ISSUE_TEMPLATE/functionality-bug-report.md
Labels: waiting-on-team-review

#3277 EDU-3748: Tweak signal vs update text
  docs/encyclopedia/application-message-passing.mdx
Labels: cross-team, tracking-internally

#3302 EDU-3823: fix typo
  docs/production-deployment/self-hosted-guide/index.mdx
Labels: community-contributor, tracking-internally

#3294 GCP: Add link to the PSC process
  docs/evaluate/temporal-cloud/gcp-private-service-connect.mdx
  docs/evaluate/temporal-cloud/security.mdx
Labels: work-in-progress

#3304 EDU-1795: Update Prometheus data source setup in Grafana
  docs/production-deployment/cloud/metrics/prometheus-grafana.mdx
  static/img/cloud/add-prometheus-api-endpoint.png
Labels: waiting-on-team-review

#3313 EDU-3858: Clarify instructions regarding Typescript setHandler
  docs/develop/typescript/message-passing.mdx
Labels: cross-team, tracking-internally

#3301 EDU-3407: Removes all legacy support and pricing
  docs/evaluate/temporal-cloud/pricing.mdx
  docs/evaluate/temporal-cloud/support.mdx
  sidebars.js
Labels: blocked-on-release

#3309 consolidate web UI pages and update to reflect yaml
  docs/references/web-ui-configuration.mdx
  docs/references/web-ui-environment-variables.mdx
  docs/references/web-ui-server-env-vars.mdx
  sidebars.js
  vercel.json
Labels: ticket?

#3311 EDU-3846: Updates nexus operations to add circuit breaking
  docs/encyclopedia/nexus-operations.mdx
  static/img/nexus/circuit-breaker.png
  static/img/nexus/circuit-breaking-no-attempts.png
  static/img/nexus/circuit-breaking.png
Labels: cross-team, do-not-merge
