Repository temporalio/documentation, pull requests merged in 2025-03, with the labels that each got.

#3404 EDU-4047: More Nexus GA polish
  docs/develop/go/temporal-nexus.mdx
  docs/develop/java/temporal-nexus.mdx
Labels: cross-team

#3341 EDU-4049: [PHP] Use typed search attributes in docs
  docs/develop/php/observability.mdx
Labels: community-contributor

#3338 EDU-4050: [PHP] add docs about `#[WorkflowInit]`
  docs/develop/php/message-passing.mdx
Labels: community-contributor

#3325 EDU-3944: TypeScript SDK: fix WithStartWorkflowOperation usage
  docs/develop/typescript/message-passing.mdx
Labels: community-contributor

#3336 EDU-3966: Fix TCLD request command reference
  docs/production-deployment/cloud/tcld/request.mdx
Labels: community-contributor

#3419 EDU-4085: Add a faq about apikey expiry limit.
  docs/production-deployment/cloud/api-keys.mdx
Labels: cross-team

#3431 EDU-4099: Clarify "only initial" for start delays w Workflow Execution
  docs/encyclopedia/workflows.mdx
Labels: docs-team

#3438 EDU-4124: Update code sample for latest Java SDK
  docs/production-deployment/cloud/api-keys.mdx
Labels: cross-team, status-check-please, ready-to-merge

#3442 EDU-4123: Add de-duplication info to pricing page
  docs/evaluate/temporal-cloud/pricing.mdx
Labels: ready-to-merge, docs-team

#3440 EDU-4116: Add pricing for (pre-release) SCIM to cloud pricing page
  docs/evaluate/temporal-cloud/pricing.mdx
Labels: docs-team

#3441 EDU-4119: Add visibility API calls to limits page
  docs/evaluate/temporal-cloud/limits.mdx
Labels: work-in-progress, docs-team

#3452 EDU-4034: Adds `tcld namespace delete-region` coverage
  docs/production-deployment/cloud/high-availability/references/regions.mdx
  docs/production-deployment/cloud/references/regions/awsregions.md
  docs/production-deployment/cloud/references/regions/gcpregions.md
  docs/production-deployment/cloud/tcld/namespace.mdx
Labels: waiting-on-tech-review, docs-team
