Repository temporalio/documentation, pull requests merged in 2025-02, with the labels that each got.

#3318 [EDU-3915] Update setting up privatelink connectivity steps with AWS UI change
  docs/evaluate/temporal-cloud/aws-privatelink.mdx
Labels: cross-team

#3324 EDU-3942: Parent Close Policy ABANDON isn't the default
  docs/develop/dotnet/child-workflows.mdx
  docs/develop/go/child-workflows.mdx
  docs/develop/java/child-workflows.mdx
  docs/develop/php/child-workflows.mdx
  docs/develop/python/child-workflows.mdx
  docs/develop/typescript/child-workflows.mdx
Labels: cross-team, tracking-internally

#3329 EDU-3950: fixes the typo for worker task queue
  sample-apps/python/schedule_your_workflow/run_worker.py
Labels: community-contributor, tracking-internally

#3241 EDU-3702: breaking apart namespaces page and updating anchors (project nova)
  docs/encyclopedia/activities.mdx
  docs/encyclopedia/clusters.mdx
  docs/encyclopedia/namespaces/global-namespaces.mdx
  docs/encyclopedia/namespaces/namespaces.mdx
  docs/evaluate/development-production-features/high-availability.mdx
  docs/glossary.md
  docs/production-deployment/self-hosted-guide/archival.mdx
  docs/production-deployment/self-hosted-guide/multi-cluster-replication.mdx
  docs/tctl-v1/namespace.mdx
  sidebars.js
Labels: waiting-on-team-review

#3315 EDU-3943: Updated FAQ section
  docs/evaluate/temporal-cloud/pricing.mdx
Labels: cross-team, tracking-internally

#3314 EDU-3861: High Availability features [Replay]
  docs/develop/java/message-passing.mdx
  docs/develop/python/message-passing.mdx
  docs/develop/typescript/message-passing.mdx
  docs/develop/worker-performance.mdx
  docs/encyclopedia/workflow-message-passing/sending-messages.mdx
  docs/encyclopedia/workflow-message-passing/workflow-message-passing.mdx
  docs/evaluate/development-production-features/cloud-vs-self-hosted.mdx
  docs/evaluate/temporal-cloud/pricing.mdx
  docs/evaluate/temporal-cloud/sla.mdx
  docs/glossary.md
  docs/production-deployment/cloud/audit-logging.mdx
  docs/production-deployment/cloud/high-availability/enable.mdx
  docs/production-deployment/cloud/high-availability/how-it-works.mdx
  docs/production-deployment/cloud/high-availability/how-to/api-authentication.mdx
  docs/production-deployment/cloud/high-availability/how-to/failovers.mdx
  docs/production-deployment/cloud/high-availability/how-to/index.mdx
  docs/production-deployment/cloud/high-availability/how-to/privatelink.mdx
  docs/production-deployment/cloud/high-availability/how-to/secure-routing.mdx
  docs/production-deployment/cloud/high-availability/index.mdx
  docs/production-deployment/cloud/high-availability/monitor.mdx
  docs/production-deployment/cloud/high-availability/references/best-practices.mdx
  docs/production-deployment/cloud/high-availability/references/concepts.mdx
  docs/production-deployment/cloud/high-availability/references/faq.mdx
  docs/production-deployment/cloud/high-availability/references/glossary.mdx
  docs/production-deployment/cloud/high-availability/references/index.mdx
  docs/production-deployment/cloud/metrics/performance-bottlenecks.mdx
  docs/production-deployment/cloud/metrics/reference.mdx
  docs/production-deployment/cloud/service-health.mdx
  docs/production-deployment/cloud/tcld/namespace.mdx
  docs/production-deployment/cloud/terraform-provider.mdx
  docs/references/events.mdx
  docs/web-ui.mdx
  sidebars.js
  src/components/infobutton/InfoButton.js
  src/components/nobreak/NoBreak.js
  src/components/pretty-image/PrettyImage.module.css
  src/components/spacer/Spacer.js
  src/components/tooltip/ToolTipTerm.js
  src/components/tooltip/deprecated/ToolTipText.js
  static/img/cloud/high-availability/active-active.png
  static/img/cloud/high-availability/active-passive.png
  static/img/cloud/high-availability/after-failover.png
  static/img/cloud/high-availability/before-failover.png
  static/img/cloud/high-availability/cell-with-multiple-namespaces.png
  static/img/cloud/high-availability/customer-environment.png
  static/img/cloud/high-availability/customer-side-example.png
  static/img/cloud/high-availability/failover-to-secondary-region.png
  static/img/cloud/high-availability/failover.png
  static/img/cloud/high-availability/private-link-old.png
  static/img/cloud/high-availability/private-link.png
  static/img/cloud/high-availability/single-region.png
  vercel.json
Labels: blocked-on-release, work-in-progress, do-not-merge

#3384 EDU-4020: add docs for namespace delete protection
  docs/production-deployment/cloud/account-setup/namespaces.mdx
Labels: cross-team, tracking-internally, checking-status

#3361 EDU-3996: Add documentation for how to connect with api keys and multi-region namespaces
  docs/cli/index.mdx
  docs/production-deployment/cloud/account-setup/certificates.mdx
  docs/production-deployment/cloud/account-setup/namespaces.mdx
  docs/production-deployment/cloud/api-keys.mdx
  docs/production-deployment/cloud/high-availability/how-to/api-authentication.mdx
Labels: cross-team, tracking-internally

#3334 EDU-3964: Update docs and samples for Nexus Go GA
  docs/develop/go/temporal-nexus.mdx
  docs/develop/go/test-suites.mdx
  docs/develop/java/temporal-nexus.mdx
  docs/encyclopedia/nexus-error-handling.mdx
  docs/encyclopedia/nexus-execution-debugging.mdx
  docs/encyclopedia/nexus-operations.mdx
  docs/encyclopedia/workers/tasks.mdx
  docs/glossary.md
  docs/references/events.mdx
  docs/references/failures.mdx
Labels: cross-team, tracking-internally, checking-status

#3391 4026: Update docs and samples for Nexus Java GA
  docs/develop/java/temporal-nexus.mdx
Labels: cross-team, tracking-internally, checking-status

#3388 EDU-4027: [PHP] Describe how to UpdateWithStart a Workflow
  docs/develop/php/message-passing.mdx
  docs/develop/php/temporal-clients.mdx
Labels: community-contributor, tracking-internally

#3379 EDU-4021: update docs for Nexus GA
  docs/develop/go/temporal-nexus.mdx
  docs/develop/java/temporal-nexus.mdx
  docs/encyclopedia/nexus-endpoints.mdx
  docs/encyclopedia/nexus-error-handling.mdx
  docs/encyclopedia/nexus-execution-debugging.mdx
  docs/encyclopedia/nexus-metrics.mdx
  docs/encyclopedia/nexus-operations.mdx
  docs/encyclopedia/nexus-registry.mdx
  docs/encyclopedia/nexus-security.mdx
  docs/encyclopedia/nexus-services.mdx
  docs/encyclopedia/nexus-use-cases.mdx
  docs/encyclopedia/nexus.mdx
  docs/encyclopedia/workflows.mdx
  docs/evaluate/development-production-features/temporal-nexus.mdx
  docs/evaluate/temporal-cloud/limits.mdx
  docs/production-deployment/cloud/nexus/index.mdx
  docs/production-deployment/cloud/nexus/latency-availability.mdx
  docs/production-deployment/cloud/nexus/limits.mdx
  docs/production-deployment/cloud/nexus/observability.mdx
  docs/production-deployment/cloud/nexus/pricing.mdx
  docs/production-deployment/cloud/nexus/security.mdx
  docs/production-deployment/self-hosted-guide/temporal-nexus.mdx
  docs/references/commands.mdx
  docs/references/errors.mdx
  docs/references/sdk-metrics.mdx
  static/img/cloud/nexus/circuit-breaking-no-attempts.png
  static/img/cloud/nexus/circuit-breaking.png
  static/img/cloud/nexus/create-nexus-endpoint-ss.png
  static/img/cloud/nexus/go-sdk-observability-async.png
  static/img/cloud/nexus/go-sdk-observability-sync.png
  static/img/cloud/nexus/nexus-bi-directional-linking.png
  static/img/cloud/nexus/nexus-billing-ss.png
  static/img/cloud/nexus/nexus-callback.png
  static/img/cloud/nexus/nexus-endpoints-ss.png
  static/img/cloud/nexus/nexus-operations-ui-search-handler.png
  static/img/cloud/nexus/nexus-operations-ui.png
  static/img/cloud/nexus/pending-nexus-operations.png
  static/img/cloud/nexus/target-namespace-ss.png
Labels: blocked-on-release, cross-team, do-not-merge

#3397 EDU-4040: [PHP] Describe how to configure API key
  docs/develop/php/core-application.mdx
  docs/develop/php/temporal-clients.mdx
Labels: community-contributor, ready-to-merge

#3375 EDU-4023: chore: update account owner language
  docs/production-deployment/cloud/account-setup/users.mdx
Labels: cross-team, status-check-please

#3387 EDU-4028: Worker Deployments Encyclopedia Entry
  docs/encyclopedia/workers/worker-deployments.mdx
  docs/production-deployment/cloud/multi-region.mdx
  sidebars.js
Labels: blocked-on-release, cross-team, do-not-merge

#3380 EDU-4029: Prepare for Worker Versioning 3.1 -- Relegate v2 docs to legacy documentation, point folks to slack
  docs/develop/dotnet/index.mdx
  docs/develop/go/index.mdx
  docs/develop/go/versioning.mdx
  docs/develop/go/worker-versioning-legacy.mdx
  docs/develop/java/index.mdx
  docs/develop/java/versioning.mdx
  docs/develop/java/worker-versioning-legacy.mdx
  docs/develop/php/index.mdx
  docs/develop/php/versioning.mdx
  docs/develop/python/index.mdx
  docs/develop/python/versioning.mdx
  docs/develop/python/worker-versioning-legacy.mdx
  docs/develop/typescript/index.mdx
  docs/develop/typescript/versioning.mdx
  docs/develop/typescript/worker-versioning-legacy.mdx
  docs/encyclopedia/workers/worker-versioning.mdx
Labels: cross-team, status-check-please
